### ISSUE TITLE
Touches not working

### ISSUE THREAD

**Issue by TomGrozev** [StefanLage/SLPagingViewSwift#24]
When I tap a button in one of the views it doesn't call the action, I have tried without SLPaging and it works. The button does the default tap animation but doesn't fire the action set in the viewcontroller's class.

**Comment by MuhammadMazharIqbal** [comment]
Hi @TomGrozev 
library has view controller retain problems please follow this solution

[https://github.com/StefanLage/SLPagingViewSwift/issues/10](https://github.com/StefanLage/SLPagingViewSwift/issues/10)
